services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - taprate

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taprate
    depends_on:
      - redis
      - db
    networks:
      - taprate

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taprate
    depends_on:
      - redis
      - db
    networks:
      - taprate

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taprate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taprate

networks:
  taprate:
    driver: bridge

volumes:
  postgres_data: