# Generated by Django 6.0.3 on 2026-04-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_nfctag'),
    ]

    operations = [
        migrations.AddField(
                model_name='survey',
                name='alert_threshold',
                field=models.IntegerField(
                    default=2,
                    help_text='Create an alert when a rating is at or below this value (1–5).',
                ),
            ),
            migrations.AddField(
                model_name='organization',
                name='alert_email',
                field=models.EmailField(
                    blank=True,
                    help_text='Email address for low-rating alert notifications. Falls back to the owner account email.',
                ),
            ),
    ]
