# Generated by Django 6.0.3 on 2026-04-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_add_alert_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='alert_email',
            field=models.EmailField(blank=True, help_text='Alert notification email. Falls back to owner account email.', max_length=254),
        ),
    ]
