# Generated by Django 6.0.3 on 2026-04-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveyset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['position']},
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='survey_surv_ip_hash_4be52f_idx',
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('owner_notified', 'Owner Notified'), ('sent', 'Sent'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='surveyset',
            name='alert_threshold',
            field=models.IntegerField(default=2, help_text='Create an alert when any rating is at or below this value (1–5).'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['session_id'], name='survey_surv_session_d4f06b_idx'),
        ),
    ]
