# Generated by Django 6.0.3 on 2026-04-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_survey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='qr_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
