# Generated by Django 6.0.1 on 2026-04-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_location_qr_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='alert_email',
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
