# Generated by Django 6.0.1 on 2026-04-21 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_organization_alert_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentive',
            name='survey',
        ),
        migrations.AddField(
            model_name='incentive',
            name='name',
            field=models.CharField(default='Unnamed Incentive', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentive',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='survey.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentive',
            name='survey_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incentives', to='survey.surveyset'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyset',
            name='review_redirect_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyset',
            name='review_redirect_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='win_rate',
            field=models.IntegerField(default=10, help_text='Percentage chance of winning (1–100)'),
        ),
        migrations.CreateModel(
            name='IncentiveWin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='survey.incentive')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='survey.surveyresponse')),
            ],
        ),
    ]
