# Generated by Django 6.0.1 on 2026-05-03 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_rename_fk_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='survey_surv_locatio_e77853_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='survey_surv_created_265304_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='survey_surv_rating_eae1fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='surveyresponse',
            name='survey_surv_session_d4f06b_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='alert_email',
            field=models.EmailField(blank=True, help_text='Alert notification email. Falls back to owner account email if blank.', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='alerts_enabled',
            field=models.BooleanField(default=True, help_text='Send email alerts when a low rating is received.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_alert_threshold',
            field=models.IntegerField(default=2, help_text='Default alert threshold for new surveys (1–5).'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_comments_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_comments_prompt',
            field=models.CharField(blank=True, default='Any additional feedback?', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_review_url',
            field=models.URLField(blank=True, help_text='Default review redirect URL for new surveys.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', help_text='IANA timezone string, e.g. America/New_York.', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='survey.surveyresponse'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='survey.organization'),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nfctag',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_tag', to='survey.location'),
        ),
        migrations.AlterField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.organization'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='survey.organization'),
        ),
    ]
