# Generated by Django 6.0.3 on 2026-05-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_remove_surveyresponse_survey_surv_locatio_e77853_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='recovery_coupon_text',
            field=models.CharField(blank=True, help_text='Coupon or offer shown as the incentive to share an email (e.g. "10% off your next visit").', max_length=200),
        ),
        migrations.AddField(
            model_name='survey',
            name='recovery_enabled',
            field=models.BooleanField(default=False, help_text='Show a recovery prompt when a low rating is submitted.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='recovery_message',
            field=models.TextField(blank=True, default="We're sorry your experience fell short. Tell us what happened and we'll make it right.", help_text='Message shown to the customer on the recovery step.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='recovery_threshold',
            field=models.IntegerField(default=3, help_text='Trigger recovery prompt when rating is at or below this value (1–5).'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='recovery_comment',
            field=models.TextField(blank=True, help_text='Customer comment submitted via the recovery prompt.'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='recovery_email',
            field=models.EmailField(blank=True, help_text='Customer email submitted via the recovery prompt.', max_length=254),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='recovery_triggered',
            field=models.BooleanField(default=False, help_text='True when this response triggered the recovery flow.'),
        ),
    ]
