# Generated by Django 6.0.3 on 2026-05-22 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_survey_recovery_coupon_text_survey_recovery_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivewin',
            name='incentive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='survey.incentive'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='survey.location'),
        ),
    ]
