# Generated by Django 6.0.3 on 2026-05-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_incentivewin_incentive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='test_mode',
            field=models.BooleanField(default=False, help_text='When enabled, all survey submissions are marked as test responses and excluded from analytics, insights, and alert emails.'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, help_text='True when submitted via dashboard preview or while org test_mode is enabled. Excluded from analytics and alert emails.'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='recovery_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='recovery_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
