# Generated by Django 6.0.3 on 2026-10-04 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_contactsubmission_organization_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='product',
            field=models.CharField(choices=[('cleanpulse', 'Cleanpulse'), ('taprate', 'TapRate')], db_index=True, default='taprate', max_length=20),
        ),
        migrations.AddField(
            model_name='incentive',
            name='product',
            field=models.CharField(choices=[('cleanpulse', 'Cleanpulse'), ('taprate', 'TapRate')], db_index=True, default='taprate', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='product',
            field=models.CharField(choices=[('cleanpulse', 'Cleanpulse'), ('taprate', 'TapRate')], db_index=True, default='taprate', max_length=20),
        ),
        migrations.AddField(
            model_name='nfctag',
            name='product',
            field=models.CharField(blank=True, choices=[('cleanpulse', 'Cleanpulse'), ('taprate', 'TapRate')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='product',
            field=models.CharField(choices=[('cleanpulse', 'Cleanpulse'), ('taprate', 'TapRate')], db_index=True, default='taprate', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(choices=[('cleanpulse', 'Cleanpulse'), ('taprate', 'TapRate')], max_length=20)),
                ('plan', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='survey.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'product'), name='unique_subscription_per_product')],
            },
        ),
    ]
