# Generated by Django 6.0.3 on 2026-10-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_copy_billing_to_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='nfc_url',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='trial_ends_at',
        ),
    ]
