# Generated by Django 6.0.3 on 2026-10-05 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_remove_org_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='issue_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('low_rating', 'Low rating'), ('issue', 'Issue reported')], default='low_rating', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='report_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('rating', 'Rating (1–5)'), ('issues', 'Issues (pick any that apply)')], default='rating', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.CreateModel(
            name='IssueOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('position', models.IntegerField(default=0)),
                ('alerts', models.BooleanField(default=True, help_text='Email the business when a customer reports this issue.')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='survey.question')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='issue_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_alerts', to='survey.issueoption'),
        ),
        migrations.CreateModel(
            name='ResponseIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='survey.issueoption')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='survey.surveyresponse')),
            ],
        ),
    ]
